#!/bin/bash

# Ensure the script is run with root privileges
if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# Update the instance's package references
apt-get update -y

# Change directory to where your docker-compose.yml file is located
cd /home/ubuntu/environment/controller-config/compose

# Pull the latest images specified in your docker-compose.yml file
docker compose pull

# Start up your Docker containers in detached mode
docker compose up -d


# Now, change directory to where your Node.js app is located
cd /home/ubuntu/environment/our-api

# Install Node.js using NodeSource's setup script for the latest version
curl -sL https://deb.nodesource.com/setup_current.x | bash -
apt-get install -y nodejs

sleep 120

# Install PM2 globally
npm install pm2 -g

# Install your application's dependencies
npm install

pm2 start api.js --name "our-api"

# Capture the output of the pm2 startup command
PM2_STARTUP_CMD=$(pm2 startup systemd -u ubuntu --hp /home/ubuntu | grep 'sudo' | sed 's/\\//g')
echo "Executing PM2 startup command: $PM2_STARTUP_CMD"
eval $PM2_STARTUP_CMD

# Save the PM2 process list and startup configuration
pm2 save

# Check PM2 logs for debugging
pm2 logs our-api --lines 100 > /var/log/pm2-our-api.log