#!/bin/bash


if [ "$EUID" -ne 0 ]; then
  echo "Please run as root"
  exit
fi

# Update the instance's package references
apt-get update -y

cd /home/ubuntu/environment/simple

curl -sL https://deb.nodesource.com/setup_current.x | bash -
apt-get install -y nodejs


npm install pm2 -g

# Install your application's dependencies
npm install

pm2 start api.js --name "simple"

# Capture the output of the pm2 startup command
PM2_STARTUP_CMD=$(pm2 startup systemd -u ubuntu --hp /home/ubuntu | grep 'sudo' | sed 's/\\//g')
echo "Executing PM2 startup command: $PM2_STARTUP_CMD"
eval $PM2_STARTUP_CMD

# Save the PM2 process list and startup configuration
pm2 save
